### ISSUE TITLE
Custom criteria checks are case sensitive

### ISSUE THREAD

**Issue by mholtmanns** [Xjph/ObservatoryExplorer#8]
Only listing this since I just ran into it.
The original example has
`PlanetClass == "Water World"`
but log files contain
`PlanetClass == "Water world"`
with lower case `world`.

Forking and creating a PR seemed like overkill.

**Comment by Xjph** [comment]
Just rewrite custom criteria completely and will be re-writing the documentation. Will pay closer attention to the capitalization in the examples!
